apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  selector:
    app: blog
    component: web
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  selector:
    matchLabels:
      app: blog
      component: web
  template:
    metadata:
      labels:
        app: blog
        component: web
    spec:
      containers:
        - image: ghost:3.0.2-alpine
          name: blog
          ports:
            - containerPort: 80
              name: http
      nodeSelector:
        beta.kubernetes.io/os: linux
