apiVersion: v1
kind: Service
metadata:
  name: pi
spec:
  selector:
    app: pi
    component: web
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pi
      component: web
  template:
    metadata:
      labels:
        app: pi
        component: web
    spec:
      containers:
        - image: sixeyed/pi-web:1911
          name: pi
          ports:
            - containerPort: 80
              name: http
      nodeSelector:
        beta.kubernetes.io/os: linux
