version: '3.7'

services:

  accesslog:
    image: diamol/ch04-access-log
    build:
      context: ch04/exercises/access-log
    networks:
      - app-net

  iotd:
    image: diamol/ch04-image-of-the-day
    build:
      context: ch04/exercises/image-of-the-day
    ports:
      - "80"
    networks:
      - app-net

  image-gallery:
    image: diamol/ch04-image-gallery
    build:
      context: ch04/exercises/image-gallery
    ports:
      - "8010:80" 
    depends_on:
      - accesslog
      - iotd
    networks:
      - app-net

networks:
  app-net: