version: '3.1'

services:

  web:
    build:
      context: ../
      dockerfile: ./docker/web/Dockerfile

  save-handler:
    build:
      context: ../
      dockerfile: ./docker/save-handler/Dockerfile