version: '3'

services:
  
  product-launch-db:
    image: microsoft/mssql-server-windows-express
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=Docker_l0nd0n
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    networks:
      - app-net

  elasticsearch:
    image: sixeyed/elasticsearch:nanoserver
    networks:
      - app-net

  kibana:
    image: sixeyed/kibana:nanoserver
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-net

  product-launch-web:
    image: sixeyed/product-launch-web:v4
    ports:
      - "80:80"
    environment:
      - DB_CONNECTION_STRING=Server=product-launch-db;Database=ProductLaunch;User Id=sa;Password=Docker_l0nd0n;
    depends_on:
      - product-launch-db
      - message-queue
    networks:
      - app-net

  save-prospect-handler:
    image: sixeyed/product-launch-save-handler:v4
    environment:
      - DB_CONNECTION_STRING=Server=product-launch-db;Database=ProductLaunch;User Id=sa;Password=Docker_l0nd0n;
    depends_on:
      - product-launch-db
      - message-queue
    networks:
      - app-net

  index-prospect-handler:
    image: sixeyed/product-launch-index-handler:v4
    depends_on:
      - elasticsearch
      - message-queue
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat