version: '3.1'

services:
  
  mta-db:
    image: microsoft/mssql-server-windows-express
    environment: 
      - ACCEPT_EULA=Y
    env_file:
      - db-credentials.env
    networks:
      - app-net

  mta-app:
    image: sixeyed/sdd2017-web:v2
    env_file:
      - db-credentials.env
    depends_on:
      - mta-db
      - message-queue
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    networks:
      - app-net

  mta-save-handler:
    image: sixeyed/sdd2017-save-handler
    env_file:
      - db-credentials.env
    depends_on:
      - mta-db
      - message-queue
    networks:
      - app-net

  elasticsearch:
    image: sixeyed/elasticsearch:nanoserver
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - app-net

  kibana:
    image: sixeyed/kibana:nanoserver
    depends_on:
      - elasticsearch
    networks:
      - app-net

  mta-index-handler:
    image: sixeyed/sdd2017-index-handler
    depends_on:
      - elasticsearch
      - message-queue
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat