apiVersion: batch/v1
kind: Job
metadata:
  name: pi-aci-stub-5000
  labels:
    demo: dc20
spec:
  template:
    spec:
      containers:
        - name: pi
          imagePullPolicy: Always
          image: sixeyed/pi:stub-dc20
          command: ["/app/Pi.Runtime.NetFx", "-dp", "5000"]
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
      restartPolicy: Never
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/role: agent
        type: virtual-kubelet
      tolerations:
        - key: virtual-kubelet.io/provider
          operator: Exists
        - key: azure.com/aci
          effect: NoSchedule
