apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: signup
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
    - host: localhost
      http:
        paths:
          - host: pi.local
            backend:
              serviceName: pi
              servicePort: http
          - host: todo.local
            backend:
              serviceName: todo
              servicePort: http
          - host: blog.local
            backend:
              serviceName: blog
              servicePort: http
