version: "3.7"

services:
  traefik:
    image: traefik:2.0.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.network=app-net"
      - "--providers.docker.exposedByDefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  pi:
    image: sixeyed/pi-web:1911
    networks:
      - app-net
    deploy:
      replicas: 3
      labels:
        - "traefik.http.routers.pi.rule=Host(`pi.local`)"
        - "traefik.http.routers.pi.entrypoints=web"
        - "traefik.http.routers.pi.middlewares=pi-redirect@docker"
        - "traefik.http.middlewares.pi-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.pi-secure.rule=Host(`pi.local`)"
        - "traefik.http.routers.pi-secure.entrypoints=web-secure"
        - "traefik.http.routers.pi-secure.tls=true"
        - "traefik.http.services.pi-service.loadbalancer.server.port=80"

  todo:
    image: diamol/ch06-todo-list
    networks:
      - app-net
    deploy:
      labels:
        - "traefik.http.routers.todo.rule=Host(`todo.local`)"
        - "traefik.http.routers.todo.entrypoints=web"
        - "traefik.http.routers.todo.middlewares=todo-redirect@docker"
        - "traefik.http.middlewares.todo-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.todo-secure.rule=Host(`todo.local`)"
        - "traefik.http.routers.todo-secure.entrypoints=web-secure"
        - "traefik.http.routers.todo-secure.tls=true"
        - "traefik.http.services.todo-service.loadbalancer.server.port=80"

  ghost:
    image: ghost:3.0.2-alpine
    networks:
      - app-net
    deploy:
      labels:
        - "traefik.http.routers.ghost.rule=Host(`blog.local`)"
        - "traefik.http.routers.ghost.entrypoints=web"
        - "traefik.http.routers.ghost.middlewares=todo-redirect@docker"
        - "traefik.http.middlewares.ghost-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.ghost-secure.rule=Host(`blog.local`)"
        - "traefik.http.routers.ghost-secure.entrypoints=web-secure"
        - "traefik.http.routers.ghost-secure.tls=true"
        - "traefik.http.services.ghost-service.loadbalancer.server.port=2368"

networks:
  app-net:
