apiVersion: v1
kind: Service
metadata:
  name: petshop-webservice
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: petshop
    component: webservice
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petshop-webservice
spec:
  selector:
    matchLabels:
      app: petshop
      component: webservice
  replicas: 2
  template:
    metadata:
      labels:
        app: petshop
        component: webservice
    spec:
      containers:
        - image: sixeyed/petshop-webservice:1809
          name: petshop-webservice
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config
              mountPath: "/petshop-webservice/config"
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: petshop-webservice-config
      nodeSelector:
        beta.kubernetes.io/os: windows
