apiVersion: v1
kind: Service
metadata:
  name: petshop-web
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: petshop
    component: web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petshop-web
spec:
  selector:
    matchLabels:
      app: petshop
      component: web
  replicas: 3
  template:
    metadata:
      labels:
        app: petshop
        component: web
    spec:
      containers:
        - image: sixeyed/petshop-web:1809
          name: petshop-web
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config
              mountPath: "/petshop-web/config"
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: petshop-web-config
      nodeSelector:
        beta.kubernetes.io/os: windows
