apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pi-api-role
  labels:
    demo: dc20
rules:
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pi-api-sa
  labels:
    demo: dc20
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pi-api-binding
  labels:
    demo: dc20
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pi-api-role
subjects:
  - kind: ServiceAccount
    name: pi-api-sa
    namespace: default

