version: '3.3'

services:
  
  signup-db:
    image: dtrlb-ynp2ligkw5fkg.westeurope.cloudapp.azure.com/demo2/signup-db
    networks:
      - app-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

  signup-app:
    image: dtrlb-ynp2ligkw5fkg.westeurope.cloudapp.azure.com/demo2/signup-web:v2
    ports:
      - "80:8090"
    depends_on:
      - signup-db
    networks:
      - app-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

networks:
  app-net: