# v2 adds the reverse proxy and new homepage
version: '3.7'

services:
  
  signup-db:
    image: dwwx/sql-server:2017
    environment:
      - sa_password=DockerCon!!!
    networks:
      - app-net
    deploy:
      placement:
        constraints:
        - node.platform.os == windows

  signup-web:
    image: dwwx/signup-web:v2
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
    depends_on:
      - signup-db
    networks:
      - app-net
    deploy:
      labels:
        - "traefik.frontend.rule=PathPrefix:/app"
        - "traefik.frontend.priority=10"        
        - "traefik.port=80"
      placement:
        constraints:
        - node.platform.os == windows

  homepage:
    image: dwwx/homepage
    networks:
      - app-net
    deploy:
      labels:
        - "traefik.frontend.rule=PathPrefix:/"
        - "traefik.frontend.priority=1"
        - "traefik.port=80"
      placement:
        constraints:
        - node.platform.os == windows

  proxy:
    image: traefik:v1.7.11-alpine
    command:
      - "--entrypoints=Name:http Address::80 Compress:true"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.watch"      
      - "--api"
    ports:
      - "8080:80"
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   
    networks:
      - app-net
    deploy:
      placement:
        constraints: 
        - node.role == manager

networks:
  app-net: