# v1 is the original monolith with SQL Server
version: '3.2'

services:

  signup-db:
    image: dwwx/sql-server:2017
    environment: 
      - sa_password=DockerCon!!!
    networks:
      - app-net
    deploy:
      placement:
        constraints:
        - node.platform.os == windows

  signup-web:
    image: dwwx/signup-web:v2
    ports:
    - "8085:80"
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
    networks:
      - app-net
    deploy:
      replicas: 2      
      placement:
        constraints:
        - node.platform.os == windows

networks:
  app-net: