version: "3.7"

services:
  todo-db:
    image: diamol/postgres:11.5
    ports:
      - "5433:5432"
    networks:
      - app-net

  todo-web:
    image: diamol/ch06-todo-list
    ports:
      - "8030:80"
    environment:
      - Database:Provider=Postgres
      - ConnectionStrings:ToDoDb=Server=todo-db;Database=todo;User Id=postgres;Password=postgres;
    depends_on:
      - todo-db
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat
