version: '3.1'

services:
  
  signup-db:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1433:1433"
    env_file:
      - db-credentials.env
    networks:
      - app-net

  message-queue:
    image: nats
    networks:
      - app-net

  save-handler:
    image: save-handler
    build:
      context: ../
      dockerfile: ./docker/save-handler/Dockerfile
    env_file:
      - db-credentials.env
    depends_on:
      - signup-db
      - message-queue
    networks:
      - app-net

  homepage:
    image: umbraco:v1
    ports:
      - "8088:80"
    networks:
      - app-net

  signup-web:
    image: signup-web:v2
    build:
      context: ../
      dockerfile: ./docker/web/Dockerfile.v2
    env_file:
      - db-credentials.env
    depends_on:
      - signup-db
      - message-queue
    networks:
      - app-net

  proxy:
    image: nginx
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - signup-web
      - homepage
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat